import type { Intern, Task } from '@/types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete Onboarding Documentation',
    description: 'Read through the company handbook and complete the acknowledgment form. This includes understanding company policies, code of conduct, and workplace guidelines.',
    status: 'in_progress',
  },
  {
    id: '2',
    title: 'Setup Development Environment',
    description: 'Install required software, configure IDE, and clone the project repository. Follow the setup guide provided in the documentation.',
    status: 'locked',
  },
  {
    id: '3',
    title: 'Complete Introduction Training',
    description: 'Watch the training videos and complete the assessment quiz. Topics include version control, coding standards, and team workflows.',
    status: 'locked',
  },
  {
    id: '4',
    title: 'First Code Review',
    description: 'Submit your first piece of code for review. This can be a small feature or bug fix assigned by your mentor.',
    status: 'locked',
  },
  {
    id: '5',
    title: 'Team Project Contribution',
    description: 'Contribute to an ongoing team project. Collaborate with team members and follow the sprint workflow.',
    status: 'locked',
  },
];

export const mockInterns: Intern[] = [
  {
    id: '1',
    profile: {
      name: 'Rahul Sharma',
      email: 'rahul.sharma@email.com',
      mobile: '+91 98765 43210',
      dob: '2001-05-15',
      address: 'Mumbai, Maharashtra',
      skills: ['JavaScript', 'React', 'Node.js'],
      domain: 'Frontend Development',
      collegeName: 'IIT Bombay',
      degree: 'B.Tech',
      branch: 'Computer Science',
      yearOfPassing: '2024',
    },
    tasks: [
      { ...mockTasks[0], status: 'approved' },
      { ...mockTasks[1], status: 'pending', submittedAt: '2024-01-15' },
      { ...mockTasks[2], status: 'locked' },
      { ...mockTasks[3], status: 'locked' },
      { ...mockTasks[4], status: 'locked' },
    ],
    registrationCompleted: true,
    registeredAt: '2024-01-01',
  },
  {
    id: '2',
    profile: {
      name: 'Priya Patel',
      email: 'priya.patel@email.com',
      mobile: '+91 87654 32109',
      dob: '2000-08-22',
      address: 'Bangalore, Karnataka',
      skills: ['Python', 'Django', 'PostgreSQL'],
      domain: 'Backend Development',
      collegeName: 'NIT Karnataka',
      degree: 'B.Tech',
      branch: 'Information Technology',
      yearOfPassing: '2024',
    },
    tasks: [
      { ...mockTasks[0], status: 'approved' },
      { ...mockTasks[1], status: 'approved' },
      { ...mockTasks[2], status: 'in_progress' },
      { ...mockTasks[3], status: 'locked' },
      { ...mockTasks[4], status: 'locked' },
    ],
    registrationCompleted: true,
    registeredAt: '2024-01-05',
  },
  {
    id: '3',
    profile: {
      name: 'Amit Kumar',
      email: 'amit.kumar@email.com',
      mobile: '+91 76543 21098',
      dob: '2001-12-10',
      address: 'Delhi, NCR',
      skills: ['Java', 'Spring Boot', 'AWS'],
      domain: 'Full Stack Development',
      collegeName: 'DTU Delhi',
      degree: 'B.Tech',
      branch: 'Computer Engineering',
      yearOfPassing: '2025',
    },
    tasks: [
      { ...mockTasks[0], status: 'in_progress' },
      { ...mockTasks[1], status: 'locked' },
      { ...mockTasks[2], status: 'locked' },
      { ...mockTasks[3], status: 'locked' },
      { ...mockTasks[4], status: 'locked' },
    ],
    registrationCompleted: true,
    registeredAt: '2024-01-10',
  },
  {
    id: '4',
    profile: {
      name: 'Sneha Reddy',
      email: 'sneha.reddy@email.com',
      mobile: '+91 65432 10987',
      dob: '2002-03-28',
      address: 'Hyderabad, Telangana',
      skills: ['UI/UX', 'Figma', 'React'],
      domain: 'Design & Frontend',
      collegeName: 'BITS Pilani',
      degree: 'B.E.',
      branch: 'Electronics & Communication',
      yearOfPassing: '2024',
    },
    tasks: [
      { ...mockTasks[0], status: 'approved' },
      { ...mockTasks[1], status: 'approved' },
      { ...mockTasks[2], status: 'approved' },
      { ...mockTasks[3], status: 'pending', submittedAt: '2024-01-18' },
      { ...mockTasks[4], status: 'locked' },
    ],
    registrationCompleted: true,
    registeredAt: '2024-01-02',
  },
];
